# Copyright ©2025 Zifeng Wang
# 2478280
# zifenw@uw.edu
# 02/28/25

CXX = g++
CXXFLAGS = -g -std=c++17 -Wall
SOURCES = ClientSide.cc ex15.cc

ex15: $(SOURCES)
		$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm -f ex15 *.o