# Copyright ©2025 Zifeng Wang
# 2478280
# zifenw@uw.edu
# 03/02/25	
CXX = g++
CXXFLAGS = -g -std=c++17 -Wall
SOURCES = ServerSide.cc ex16.cc

ex16: $(SOURCES)
		$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm -f ex16 *.o